/** @type {import('tailwindcss').Config} */
import flowbite from "flowbite/plugin";
import forms from "@tailwindcss/forms";
import typography from "@tailwindcss/typography";

module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./node_modules/flowbite-react/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "bg-default": "hsl(var(--bg-default))",
        "bg-surface": "hsl(var(--bg-surface))",
        "bg-alt": "hsl(var(--bg-alt))",
        "bg-interactive": "hsl(var(--bg-interactive))",
        "bg-hover": "hsl(var(--bg-hover))",
        "bg-active": "hsl(var(--bg-active))",
        "bg-disabled": "hsl(var(--bg-disabled))",

        "text-default": "hsl(var(--text-default))",
        "text-secondary": "hsl(var(--text-secondary))",
        "text-muted": "hsl(var(--text-muted))",
        "text-placeholder": "hsl(var(--text-placeholder))",
        "text-link": "hsl(var(--text-link))",
        "text-link-hover": "hsl(var(--text-link-hover))",
        "text-on-primary": "hsl(var(--text-on-primary))",
        "text-on-secondary": "hsl(var(--text-on-secondary))",
        "text-on-accent": "hsl(var(--text-on-accent))",
        "text-on-dark": "hsl(var(--text-on-dark))",
        "text-primary": "hsl(var(--text-primary))",

        "border-default": "hsl(var(--border-default))",
        "border-surface": "hsl(var(--border-surface))",
        "border-interactive": "hsl(var(--border-interactive))",
        "border-focus": "hsl(var(--border-focus))",
        "border-disabled": "hsl(var(--border-disabled))",

        "ring-default": "hsl(var(--ring-default))",

        "primary-default": "hsl(var(--primary-default))",
        "primary-hover": "hsl(var(--primary-hover))",
        "primary-active": "hsl(var(--primary-active))",

        "secondary-default": "hsl(var(--secondary-default))",
        "secondary-hover": "hsl(var(--secondary-hover))",
        "secondary-active": "hsl(var(--secondary-active))",

        "accent-default": "hsl(var(--accent-default))",
        "accent-hover": "hsl(var(--accent-hover))",
        "accent-active": "hsl(var(--accent-active))",

        "status-success-bg": "hsl(var(--status-success-bg))",
        "status-success-border": "hsl(var(--status-success-border))",
        "status-success-text": "hsl(var(--status-success-text))",

        "status-warning-bg": "hsl(var(--status-warning-bg))",
        "status-warning-border": "hsl(var(--status-warning-border))",
        "status-warning-text": "hsl(var(--status-warning-text))",

        "status-danger-bg": "hsl(var(--status-danger-bg))",
        "status-danger-border": "hsl(var(--status-danger-border))",
        "status-danger-text": "hsl(var(--status-danger-text))",

        "status-info-bg": "hsl(var(--status-info-bg))",
        "status-info-border": "hsl(var(--status-info-border))",
        "status-info-text": "hsl(var(--status-info-text))",

        primary: {
          DEFAULT: "hsl(var(--primary-default))",
          foreground: "hsl(var(--text-on-primary))",
          50: "hsl(var(--color-primary-50))",
          100: "hsl(var(--color-primary-100))",
          200: "hsl(var(--color-primary-200))",
          300: "hsl(var(--color-primary-300))",
          400: "hsl(var(--color-primary-400))",
          500: "hsl(var(--color-primary-500))",
          600: "hsl(var(--color-primary-600))",
          700: "hsl(var(--color-primary-700))",
          800: "hsl(var(--color-primary-800))",
          900: "hsl(var(--color-primary-900))",
          950: "hsl(var(--color-primary-950))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary-default))",
          foreground: "hsl(var(--text-on-secondary))",
          50: "hsl(var(--color-secondary-50))",
          100: "hsl(var(--color-secondary-100))",
          200: "hsl(var(--color-secondary-200))",
          300: "hsl(var(--color-secondary-300))",
          400: "hsl(var(--color-secondary-400))",
          500: "hsl(var(--color-secondary-500))",
          600: "hsl(var(--color-secondary-600))",
          700: "hsl(var(--color-secondary-700))",
          800: "hsl(var(--color-secondary-800))",
          900: "hsl(var(--color-secondary-900))",
          950: "hsl(var(--color-secondary-950))",
        },
        neutral: {
          DEFAULT: "hsl(var(--text-default))",
          foreground: "hsl(var(--neutral-foreground))",
          50: "hsl(var(--color-neutral-50))",
          100: "hsl(var(--color-neutral-100))",
          200: "hsl(var(--color-neutral-200))",
          300: "hsl(var(--color-neutral-300))",
          400: "hsl(var(--color-neutral-400))",
          500: "hsl(var(--color-neutral-500))",
          600: "hsl(var(--color-neutral-600))",
          700: "hsl(var(--color-neutral-700))",
          800: "hsl(var(--color-neutral-800))",
          900: "hsl(var(--color-neutral-900))",
          950: "hsl(var(--color-neutral-950))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent-default))",
          foreground: "hsl(var(--text-on-accent))",
          50: "hsl(var(--color-accent-50))",
          100: "hsl(var(--color-accent-100))",
          200: "hsl(var(--color-accent-200))",
          300: "hsl(var(--color-accent-300))",
          400: "hsl(var(--color-accent-400))",
          500: "hsl(var(--color-accent-500))",
          600: "hsl(var(--color-accent-600))",
          700: "hsl(var(--color-accent-700))",
          800: "hsl(var(--color-accent-800))",
          900: "hsl(var(--color-accent-900))",
          950: "hsl(var(--color-accent-950))",
        },
        "bg-light": {
          50: "hsl(var(--color-background-light-50))",
          100: "hsl(var(--color-background-light-100))",
          200: "hsl(var(--color-background-light-200))",
          300: "hsl(var(--color-background-light-300))",
          400: "hsl(var(--color-background-light-400))",
          500: "hsl(var(--color-background-light-500))",
          600: "hsl(var(--color-background-light-600))",
          700: "hsl(var(--color-background-light-700))",
          800: "hsl(var(--color-background-light-800))",
          900: "hsl(var(--color-background-light-900))",
          950: "hsl(var(--color-background-light-950))",
        },
        "bg-dark": {
          50: "hsl(var(--color-background-dark-50))",
          100: "hsl(var(--color-background-dark-100))",
          200: "hsl(var(--color-background-dark-200))",
          300: "hsl(var(--color-background-dark-300))",
          400: "hsl(var(--color-background-dark-400))",
          500: "hsl(var(--color-background-dark-500))",
          600: "hsl(var(--color-background-dark-600))",
          700: "hsl(var(--color-background-dark-700))",
          800: "hsl(var(--color-background-dark-800))",
          900: "hsl(var(--color-background-dark-900))",
          950: "hsl(var(--color-background-dark-950))",
        },
      },
    },
  },
  plugins: [flowbite, forms, typography],
};
